baseURL = "http://www.jiangyuqin.com/"
languageCode = "zh-Hans"
title = "布洛阁 - Heaven Jiang"
theme = "AllinOne"

[permalinks]
  blog                     = "blog/:year-:month/:slug/"

[taxonomies]
  category                 = "categories"
  series                   = "series"
  tag                      = "tags"

[menu]
  [[menu.main]]
    name                   = "Post"
    weight                 = -120
    identifier             = "post"
    url                    = "post/"  

  [[menu.main]]
    name                   = "Moment"
    weight                 = -110
    identifier             = "moment"
    url                    = "moment/" 

  [[menu.main]]
    name                   = "About"
    weight                 = -100
    identifier             = "about"
    url                    = "about/"  

 
[params]
# AllinOne Config Start

 faviconfile              = "img/airplane-big.png"               # from static/
 avatar                   = "img/profile-heaven.jpg"             # path to image in static dir e.g img/avatar.png 
 author                   = "Heaven Jiang"
 description              = ["中国匠人 蒋宇钦.", "Love the wonderful world.", "Do the right things and be a better man."]           # appears in the site header when set to a non-empty string
 welcome_head             = "Hello, World!"
 welcome_word             = "~ No Day But Today ~"
 latestpostscount         = 5                             # how many posts to display on the home page
 bloggroupby              = 'month'
 dateform                 = "Jan 2, 2006"
 dateformfull             = "2006-01-02  Monday  15:04:05"
 noshowreadtime           = false                         # if true, don't show "<x> minutes read" in posts


# if you want to use images in the theme (defult in the theme)
slidesDirPath              = "themes/AllinOne/static/img/header-slides"  
slidesDirPathURL           = "img/header-slides"

# if you want to use images in static/img/header-slides
# slidesDirPath            = "static/img/header-slides"
# slidesDirPathURL         = "img/header-slides"

# highlighting 
  highlightjs              = true
# latex
  katex                    = true
# links
  email                    = "admin@jiangyuqin.com"
  github                   = "//github.com/jheaven"
  linkedin                 = "//linkedin.com/in/you"
  facebook                 = "//facebook.com/you"
  googleplus               = "//google.com/you"
  twitter                  = "//twitter.com/you" 
  px500                    = "//px500"
  instagram                = "//instagram.com/you"
  include_rss              = true                          # include RSS <link> tag in <head> and show RSS icon
  
  # analytics
  googleAnalytics          = "your-google-analytic-id"

  hasCJKLanguage = true

# AllinOne Config End
